---
apiVersion: v1
kind: Service
metadata:
  name: gnmic-metrics-service
  namespace: default
  labels:
    app.kubernetes.io/name: gnmic-router-metrics
spec:
  selector:
    # This grabs your gnmic pods
    operator.gnmic.dev/cluster: telemetry-cluster 
  ports:
    - name: prom-metrics
      port: 9804
      targetPort: 10124  # <--- The magic fix! Routing to the actual port.
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gnmic-telemetry
  labels:
    release: stable  
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gnmic-router-metrics
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: prom-metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s