---
apiVersion: v1
kind: Service
metadata:
  name: gnmic-metrics-service-10124
  namespace: default
  labels:
    app.kubernetes.io/name: gnmic-router-metrics-10124
spec:
  selector:
    # This grabs your gnmic pods
    operator.gnmic.dev/cluster: telemetry-cluster 
  ports:
    - name: prom-metrics
      port: 10124         # Explicitly use the real port
      targetPort: 10124   # Explicitly target the real port
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gnmic-telemetry-10124
  labels:
    release: stable  
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gnmic-router-metrics-10124
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: prom-metrics  # Prometheus will now scrape 10124
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s